### ISSUE TITLE
psi4 fails to find libefp: missing component: shallow fraglib

### ISSUE THREAD

**Issue by yurivict** [ilyak/libefp#11]
```
-- libefpConfig missing component: shallow fraglib (libefp: /usr/local/share/libefp/fraglib;/usr/local/share/libefp/fraglib/databases)
```

Both directories ```/usr/local/share/libefp/fraglib and ```/usr/local/share/libefp/fraglib/databases``` exist and have .efp files.

What's wrong?

**Comment by loriab** [comment]
Need to flip [this](https://github.com/ilyak/libefp/blob/master/CMakeLists.txt#L25) to `OFF` as "Psi4 wants OFF" advises. That way there won't be two fraglib dirs, just one flat one.

May also want to note other "Psi4 wants" in the CMakeLists.txt, and for future-proofing, turn `INSTALL_DEVEL_HEADERS=ON`.

**Comment by yurivict** [comment]
> Need to flip this to OFF as "Psi4 wants OFF" advises. That way there won't be two fraglib dirs, just one flat one.

It should build with both ON/OFF?

**Comment by loriab** [comment]
Psi4 expects it off. I don't know if any other of libefp's downstream users care.

**Comment by yurivict** [comment]
I tried to build it with default parameters and found that it fails.
Why not delete this option is it isn't needed?

**Comment by loriab** [comment]
I'm not following. I just tried a build/install with all default parameters, and it's fine. What specific error are you hitting?

On the `FRABLIB_DEEP`, it seemed fair play to keep the directory structure of the orig developer by default but, since Psi needed something a little different, enable it by toggle.

**Comment by yurivict** [comment]
It builds itself. But dependent packages with the error in my OP.

**Comment by loriab** [comment]
Right, I've reproduced locally your original error with a pure default libefp build + Psi4 and confirmed that the solution in my first response resolves the problem.

What is the error associated with any further problem? Are you dealing with more than Psi as downstream from libefp?

**Comment by yurivict** [comment]
No further errors. Only for psi4 downstream.
I am ok, I created the FreeBSD port for libefp - it is fine now. -)

You just need to fix it so that it doens't break with any option selections.

**Comment by ilyak** [comment]
Should I close this as resolved?

**Comment by yurivict** [comment]
Yes, thanks!
