### ISSUE TITLE
inconsistency in screen_damping function 

### ISSUE THREAD

**Issue by tzyii** [ilyak/libefp#7]
In libefp, when alpha=gamma, screen=1.0 - (1.0 + 0.5 * alpha * beta) * exp(-pi * r). But in Slipchenko†, L. V. and M. S. Gordon (2010). "Damping functions in the effective fragment potential method." Molecular Physics 107(8-12): 999-1016, there is no 0.5 in P(0) when alpha=beta. Which is why?

**Comment by ilyak** [comment]
The code in libefp should be correct. It agrees with GAMESS. Looks like it is a typo in paper but I haven't received confirmation from Slipchenko.
