### ISSUE TITLE
pol tests

### ISSUE THREAD

**Issue by loriab** [ilyak/libefp#8]
While I can easily reproduce total efp energies and elec, xr, and disp components, and all (including pol) components coded up as psi4 test cases, I'm not able to compute the pol components in the libefp test cases. Moreover, the components don't sum to the total. Can you suggest where the numbers or my reasoning is going wrong? I have the same problem for all 6 pol_[1-3][ab] tests.

```
elec_1a.in	 0.0002900482
pol_1a.in 	 0.0002777238
xr_1.in	 	 0.0000134716
disp_1a.in	-0.0000989033
		-------------
		 0.0004823403	

total_1a.in	 0.0001922903
```

**Comment by ilyak** [comment]
When you compute the polarization component, you must also enable electrostatics (since something must induce the dipoles). So in pol_1a you have "terms elec pol", and you double-count some of the electrostatics if you add it to elec_1a. Pol_1a+disp_1a+xr_1 add up to a total.

**Comment by loriab** [comment]
Got it, all passing now. Thanks!
